language: node_js
node_js:
- '5'
after_success:
- codecov
deploy:
  provider: npm
  api_key:
    secure: fAu44XC0DLj82FOqAaDDOBvzgkI1dT5Yh9pfWt41nJFCrVXqJwRgA+avvVmtAQ+7H8wNdK0ulU9J/l6rvPkPs2AH0r8OyJ5r2rJBNcfgZtz2H667AHlvWYlQRKg+WD79YXmxH8Mgz4V47UC6VWJiLnXjHtaOL7WmPivMbOyIX5lC/BEu7UPTF1d3zFjzr99HzFAWutzkcTvdxkhD78soQkdabP3lIpf8wZx+YEWa6G1fu7+PPrYGTrmrdk4dVb5/cDEiRmBG8BRf8NxzfoMNFD/68MJ/QvpQmL6jp/tX8+ZH+Vx5v2ZRIRZ9VOqEReN3gBoBRX4HwZoAv/RRL9U5mEFD/PdjWEacvrhiIf0kp93HjBIhHnR8LQm/RXlNDbyj5erbkriOj59yXIVziFfIGTzIhyTWrZ9SAUyoSPbTz37sP6b40mdwK/b0pU7a12MGgIIDxYta15cM/3RFjl6c/4fhWHjzRyjAaZEHmNqdu1AWpAk4BEpvMDAA7FIpAczty5WSJAmV5rIzz/zfPLwyCkY/4fnTnx5djH+YhF92pEYq1SlHLvJvQQHxjggQcDvdjEXUAL4eyteBuZNAjPhVWErQl7bQYPTCXrk+NvQ2/jv71tJIE0W9ZPK5PZAborvMzjZ7EeQmupsjbdFjN+TccZtfeUMaz9FA2/BskitX4hQ=
