language: node_js
node_js:
- '5'
after_success:
- codecov
deploy:
  provider: npm
  email: org.yi.dttvb@gmail.com
  api_key:
    secure: rTQk3SwZuAjeR4TzSkUuBqMii0dIboIfauDg2nq5FHhPw6OZyUdj6I17YxEl1K0e34STc8Y2CqA9RzmSlYh4tBtyZdNV4Usgyjm+P2EkbtXJm1nP2v/WYuXaJ2XmPjWLXLJgWC/cUdY9NODnp5VvDnJK+X4CeZ5UlvgrfIYs1xnn+kSEgHFkOgGsjft6Cqumh8BkPKUIWYGAQlxMtaT5cSsf62Fq4hwl7b7GVJ9db+imCjRr09H0h2EQjLJiWtOGVW6tZXTyC/gOiOqQZVxLMpMpu0DpimeRKlBey05BUifU1aBWDvLlRZbHpSjYrdDTctwImmfzKM4v/UfS1/+b+bVyI5IWl5VUmf0vcfV6Pc2Az4KhgRbe4dGmhAyjqoHaB/ovbIfyLGP37UMHd1atulYYA+XSyo01lvKw2J+EeIsFL2obuTBHTptL0RYawdFPFx8EhVwPcjg9Aj0srCXDJ7zAoB8PmH/L5UzjbbpidNVyQqiKTzQWuBxnkbtSRf6zCRzG874VszThpgEhykuqeY/qMMccteBAS5mbOjwtWifQhyGBDMeE40vfVRUXLKw9AgOjCm+ZAe6KXAW/3H0h4EQN3dWWmjTqyxVfNdLuaxEYqQ96BsVmJIGPKOdf5QJdeF/949t7ZH8nY5tMFaI7zcHLgoonADw2bzJUZzX3LY0=
  on:
    tags: true
    repo: dtinth/babel-plugin-__coverage__
